title: Mohd Zubair
logo: /assets/img/headshot.png
description: MBA in Finance with 10 years of experience in the field of Finance and Accounts. Seeking assessments in Business Finance Analysis in a competitive corporate environment to make a significant contribution to the financial stability of the firm. Preferably in Financial Services/ Banking/ IT/ KPO sectors
theme: jekyll-theme-minimal
